# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface
# Build directory: /home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_planners_chomp_rostest_test_chomp_moveit_rrbot.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp/test_results/moveit_planners_chomp/rostest-test_chomp_moveit_rrbot.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface --package=moveit_planners_chomp --results-filename test_chomp_moveit_rrbot.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface/test/chomp_moveit_rrbot.test ")
set_tests_properties(_ctest_moveit_planners_chomp_rostest_test_chomp_moveit_rrbot.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface/CMakeLists.txt;61;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface/CMakeLists.txt;0;")
add_test(_ctest_moveit_planners_chomp_rostest_test_chomp_moveit_panda.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp/test_results/moveit_planners_chomp/rostest-test_chomp_moveit_panda.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface --package=moveit_planners_chomp --results-filename test_chomp_moveit_panda.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_planners_chomp/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface/test/chomp_moveit_panda.test ")
set_tests_properties(_ctest_moveit_planners_chomp_rostest_test_chomp_moveit_panda.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface/CMakeLists.txt;68;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface/CMakeLists.txt;0;")
subdirs("gtest")
