# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionAction.msg;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionActionGoal.msg;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionActionResult.msg;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionActionFeedback.msg;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionGoal.msg;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionResult.msg;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg/ObjectRecognitionFeedback.msg;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg/ObjectType.msg;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg/ObjectInformation.msg;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg/RecognizedObject.msg;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg/RecognizedObjectArray.msg;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg/Table.msg;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg/TableArray.msg"
services_str = "/home/mu/IVG/ws_moveit/src/object_recognition_msgs/srv/GetObjectInformation.srv"
pkg_name = "object_recognition_msgs"
dependencies_str = "actionlib_msgs;geometry_msgs;sensor_msgs;shape_msgs;std_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "object_recognition_msgs;/home/mu/IVG/ws_moveit/devel_isolated/object_recognition_msgs/share/object_recognition_msgs/msg;object_recognition_msgs;/home/mu/IVG/ws_moveit/src/object_recognition_msgs/msg;actionlib_msgs;/home/mu/IVG/ros_catkin_ws/install_isolated/share/actionlib_msgs/cmake/../msg;geometry_msgs;/home/mu/IVG/ros_catkin_ws/install_isolated/share/geometry_msgs/cmake/../msg;sensor_msgs;/home/mu/IVG/ros_catkin_ws/install_isolated/share/sensor_msgs/cmake/../msg;shape_msgs;/home/mu/IVG/ros_catkin_ws/install_isolated/share/shape_msgs/cmake/../msg;std_msgs;/home/mu/IVG/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/home/mu/IVG/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
