#!/usr/bin/env python3
"""OBJ/MTL 程序网格生成工具 — 纯 stdlib，零 ROS/Gazebo 依赖。

为 orchard_scene 渲染级（HD）世界产出轻量程序网格（视觉用，碰撞仍用
几何版的粗包络基元）：

  leaf_blob_a.obj / leaf_blob_b.obj  加噪 icosphere 叶团（两种叶色）
  tapered_cyl.obj                    +z 向单位锥柱（z∈[0,1]，底半径 1→顶 taper）
  bag.obj                            套袋纸袋（收口在原点，纸身沿 -z，单位尺寸）

所有网格右手系、含 vn 法线；材质集中写在同目录 materials.mtl。
HD 世界用 SDF <scale> 逐实例缩放复用这几份网格。
"""
from __future__ import annotations

import math
from pathlib import Path

# 与 generate_orchard_world.py 的配色保持一致（线性 RGB 近似）。
MATERIALS = {
    'leaf_a': (0.20, 0.45, 0.15),
    'leaf_b': (0.26, 0.52, 0.18),
    'bark': (0.47, 0.35, 0.23),
    'kraft_a': (0.82, 0.64, 0.30),
    'kraft_b': (0.78, 0.60, 0.27),
}


def _norm3(v):
    n = math.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2)
    return (v[0] / n, v[1] / n, v[2] / n)


def icosphere(subdiv: int, noise_fn=None):
    """单位 icosphere。noise_fn(单位方向)->径向系数，None 则为纯球。

    返回 (verts, faces)；verts 为三元组列表，faces 为顶点索引三元组。
    subdiv=2 → 162 顶点 / 320 面，够叶团与果袋的观感。
    """
    phi = (1.0 + 5.0 ** 0.5) / 2.0
    verts = [
        (-1, phi, 0), (1, phi, 0), (-1, -phi, 0), (1, -phi, 0),
        (0, -1, phi), (0, 1, phi), (0, -1, -phi), (0, 1, -phi),
        (phi, 0, -1), (phi, 0, 1), (-phi, 0, -1), (-phi, 0, 1),
    ]
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    verts = [_norm3(v) for v in verts]
    for _ in range(subdiv):
        cache = {}

        def mid(a, b):
            key = (a, b) if a < b else (b, a)
            if key not in cache:
                cache[key] = len(verts)
                verts.append(_norm3((
                    verts[a][0] + verts[b][0],
                    verts[a][1] + verts[b][1],
                    verts[a][2] + verts[b][2])))
            return cache[key]

        new_faces = []
        for a, b, c in faces:
            ab, bc, ca = mid(a, b), mid(b, c), mid(c, a)
            new_faces += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = new_faces
    if noise_fn is not None:
        verts = [tuple(c * noise_fn(v) for c in v) for v in verts]
    return verts, faces


def compute_vnormals(verts, faces):
    """面积加权顶点法线（OBJ vn），输入 verts 可为任意尺度。"""
    acc = [[0.0, 0.0, 0.0] for _ in verts]
    for a, b, c in faces:
        va, vb, vc = verts[a], verts[b], verts[c]
        e1 = (vb[0] - va[0], vb[1] - va[1], vb[2] - va[2])
        e2 = (vc[0] - va[0], vc[1] - va[1], vc[2] - va[2])
        n = (e1[1] * e2[2] - e1[2] * e2[1],
             e1[2] * e2[0] - e1[0] * e2[2],
             e1[0] * e2[1] - e1[1] * e2[0])
        for i in (a, b, c):
            acc[i][0] += n[0]
            acc[i][1] += n[1]
            acc[i][2] += n[2]
    return [_norm3(v) if (v[0] or v[1] or v[2]) else (0.0, 0.0, 1.0) for v in acc]


def tapered_cyl(segments: int = 16, taper: float = 0.72):
    """单位锥柱：底面 z=0 半径 1，顶面 z=1 半径 taper，含端盖。"""
    verts, norms, faces = [], [], []
    for i in range(segments):
        a = 2.0 * math.pi * i / segments
        ca, sa = math.cos(a), math.sin(a)
        verts.append((ca, sa, 0.0))
        norms.append(_norm3((ca, sa, 0.18)))
        verts.append((ca * taper, sa * taper, 1.0))
        norms.append(_norm3((ca, sa, 0.18)))
    for i in range(segments):
        j = (i + 1) % segments
        faces.append((2 * i, 2 * j, 2 * j + 1))
        faces.append((2 * i, 2 * j + 1, 2 * i + 1))
    for zc, ncap, cap_sign in ((1.0, (0.0, 0.0, 1.0), 1), (0.0, (0.0, 0.0, -1.0), -1)):
        ring0 = len(verts)
        center = len(verts) + segments
        verts.append((0.0, 0.0, zc))
        norms.append(ncap)
        for i in range(segments):
            a = 2.0 * math.pi * i / segments
            r = 1.0 if zc > 0.5 else taper
            verts.append((math.cos(a) * r, math.sin(a) * r, zc))
            norms.append(ncap)
        for i in range(segments):
            j = (i + 1) % segments
            if cap_sign > 0:
                faces.append((center, ring0 + i, ring0 + j))
            else:
                faces.append((center, ring0 + j, ring0 + i))
    return verts, faces, norms


def bag_shape(subdiv: int = 2):
    """套袋纸袋：收口在 z=0（袋口/扎口处），纸身沿 -z 到 -1（袋底）。

    单位半径、单位长度；r(t)=sin(pi*u)^2，收口≈0.1R，中部鼓起≈R，底部收圆。
    返回 (verts, faces, norms)。
    """
    verts, faces = icosphere(subdiv)
    shaped = []
    for nx, ny, nz in verts:
        t = (1.0 - nz) / 2.0
        u = min(1.0, 0.10 + 0.90 * t)
        r = math.sin(math.pi * u) ** 2
        shaped.append((nx * r, ny * r, -t))
    return shaped, faces, compute_vnormals(shaped, faces)


def write_obj(path: Path, name: str, verts, faces, norms, material: str):
    lines = [
        f'# {name} — generated by orchard_scene/tools/meshgen.py',
        'mtllib ../materials/materials.mtl',
        f'o {name}',
    ]
    lines += [f'v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}' for v in verts]
    lines += [f'vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}' for n in norms]
    lines.append(f'usemtl {material}')
    lines += [
        f'f {a + 1}//{a + 1} {b + 1}//{b + 1} {c + 1}//{c + 1}'
        for a, b, c in faces
    ]
    path.write_text('\n'.join(lines) + '\n')


def write_mtl(path: Path):
    lines = ['# materials.mtl — generated by orchard_scene/tools/meshgen.py']
    for name, (r, g, b) in MATERIALS.items():
        lines += [
            f'newmtl {name}',
            f'Ka {r * 0.35:.4f} {g * 0.35:.4f} {b * 0.35:.4f}',
            f'Kd {r:.4f} {g:.4f} {b:.4f}',
            'Ks 0.03 0.03 0.03',
            'Ns 8.0',
            'illum 2',
            '',
        ]
    path.write_text('\n'.join(lines))


def build_assets(meshes_dir: Path, materials_dir: Path, rng) -> dict:
    """产出全部网格资产；返回 {名称: (顶点数, 面数)} 统计。"""
    meshes_dir.mkdir(parents=True, exist_ok=True)
    materials_dir.mkdir(parents=True, exist_ok=True)
    write_mtl(materials_dir / 'materials.mtl')
    stats = {}

    blob_a, faces = icosphere(2, noise_fn=lambda v: 1.0 + rng.uniform(-0.16, 0.16))
    blob_a_n = compute_vnormals(blob_a, faces)
    write_obj(meshes_dir / 'leaf_blob_a.obj', 'leaf_blob_a', blob_a, faces, blob_a_n, 'leaf_a')
    stats['leaf_blob_a'] = (len(blob_a), len(faces))

    blob_b, faces = icosphere(2, noise_fn=lambda v: 1.0 + rng.uniform(-0.16, 0.16))
    blob_b_n = compute_vnormals(blob_b, faces)
    write_obj(meshes_dir / 'leaf_blob_b.obj', 'leaf_blob_b', blob_b, faces, blob_b_n, 'leaf_b')
    stats['leaf_blob_b'] = (len(blob_b), len(faces))

    cv, cf, cn = tapered_cyl()
    write_obj(meshes_dir / 'tapered_cyl.obj', 'tapered_cyl', cv, cf, cn, 'bark')
    stats['tapered_cyl'] = (len(cv), len(cf))

    bv, bf, bn = bag_shape()
    write_obj(meshes_dir / 'bag_a.obj', 'bag_a', bv, bf, bn, 'kraft_a')
    stats['bag_a'] = (len(bv), len(bf))

    write_obj(meshes_dir / 'bag_b.obj', 'bag_b', bv, bf, bn, 'kraft_b')
    stats['bag_b'] = (len(bv), len(bf))
    return stats
