# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo
# Build directory: /home/mu/IVG/ws_moveit/build_isolated/moveit_servo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_servo_rostest_test_basic_servo_tests.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/test_results/moveit_servo/rostest-test_basic_servo_tests.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo --package=moveit_servo --results-filename test_basic_servo_tests.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/test/basic_servo_tests.test ")
set_tests_properties(_ctest_moveit_servo_rostest_test_basic_servo_tests.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/CMakeLists.txt;160;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/CMakeLists.txt;0;")
add_test(_ctest_moveit_servo_rostest_test_servo_cpp_interface_test.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/test_results/moveit_servo/rostest-test_servo_cpp_interface_test.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo --package=moveit_servo --results-filename test_servo_cpp_interface_test.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/test/servo_cpp_interface_test.test ")
set_tests_properties(_ctest_moveit_servo_rostest_test_servo_cpp_interface_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/CMakeLists.txt;170;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/CMakeLists.txt;0;")
add_test(_ctest_moveit_servo_rostest_test_pose_tracking_test.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/test_results/moveit_servo/rostest-test_pose_tracking_test.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo --package=moveit_servo --results-filename test_pose_tracking_test.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_servo/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/test/pose_tracking_test.test ")
set_tests_properties(_ctest_moveit_servo_rostest_test_pose_tracking_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/CMakeLists.txt;180;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/moveit_servo/CMakeLists.txt;0;")
subdirs("gtest")
