"""Zero-ROS mirror of peach2_interfaces/msg/FailureCode.msg (values must stay identical)."""

NONE = 0

PERCEPTION_NO_TARGET = 10
PERCEPTION_EXACT_TF_MISSING = 11
PERCEPTION_LOW_QUALITY = 12
PERCEPTION_OUT_OF_SCOPE = 13

MODEL_NOT_CONVERGED = 20
MODEL_STALE = 21
MODEL_EXPIRED = 22
BUDGET_RADIAL_NEGATIVE = 23
BUDGET_AXIAL_NEGATIVE = 24
BUDGET_STRUCTURAL = 25
NECK_REMEASURE_MISMATCH = 26
SWING_TOO_LARGE = 27
NECK_REMEASURE_PENDING = 28

PLAN_NO_IK = 30
PLAN_COLLISION = 31
PLAN_FAILED = 32
PLAN_CARTESIAN_INCOMPLETE = 33

EXEC_FAILED = 40
EXEC_TIMEOUT = 41
CONTACT_ABORT = 42
PREGRASP_RESIDUAL = 43
RETREAT_FAILED = 44
TARGET_TIMEOUT = 45

TOOL_NOT_OPEN = 50
TOOL_COMMAND_FAILED = 51
TOOL_FEEDBACK_TIMEOUT = 52
CUT_NOT_CONFIRMED = 53
TOOL_FAULT = 54
TOOL_NOT_FEASIBLE = 55

SAFETY_GATE_CLOSED = 60
ROBOT_NOT_READY = 61
CANCELED = 62
RECOVERY_REQUIRED = 63
ENVIRONMENT_UNSAFE = 64
DEPENDENCY_UNAVAILABLE = 65


def all_codes() -> dict[str, int]:
    return {k: v for k, v in globals().items() if k.isupper() and isinstance(v, int)}
