set(_CATKIN_CURRENT_PACKAGE "rqt_web")
set(rqt_web_VERSION "0.4.11")
set(rqt_web_MAINTAINER "Scott Logan <scott@openrobotics.org>")
set(rqt_web_PACKAGE_FORMAT "3")
set(rqt_web_BUILD_DEPENDS )
set(rqt_web_BUILD_EXPORT_DEPENDS )
set(rqt_web_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(rqt_web_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_web_EXEC_DEPENDS "python_qt_binding" "python-rospkg" "python3-rospkg" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py" "webkit_dependency")
set(rqt_web_EXEC_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_web_RUN_DEPENDS "python_qt_binding" "python-rospkg" "python3-rospkg" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py" "webkit_dependency")
set(rqt_web_RUN_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_web_TEST_DEPENDS )
set(rqt_web_DOC_DEPENDS )
set(rqt_web_URL_WEBSITE "http://wiki.ros.org/rqt_web")
set(rqt_web_URL_BUGTRACKER "https://github.com/ros-visualization/rqt_web/issues")
set(rqt_web_URL_REPOSITORY "https://github.com/ros-visualization/rqt_web")
set(rqt_web_DEPRECATED "")