# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl
# Build directory: /home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf2_kdl_rostest_test_test.launch "/home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl/test_results/tf2_kdl/rostest-test_test.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl --package=tf2_kdl --results-filename test_test.xml --results-base-dir \"/home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl/test_results\" /home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl/test/test.launch ")
set_tests_properties(_ctest_tf2_kdl_rostest_test_test.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl/CMakeLists.txt;54;add_rostest;/home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl/CMakeLists.txt;0;")
add_test(_ctest_tf2_kdl_rostest_test_test_python.launch "/home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl/test_results/tf2_kdl/rostest-test_test_python.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl --package=tf2_kdl --results-filename test_test_python.xml --results-base-dir \"/home/mu/IVG/ros_catkin_ws/build_isolated/tf2_kdl/test_results\" /home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl/test/test_python.launch ")
set_tests_properties(_ctest_tf2_kdl_rostest_test_test_python.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl/CMakeLists.txt;55;add_rostest;/home/mu/IVG/ros_catkin_ws/src/geometry2/tf2_kdl/CMakeLists.txt;0;")
subdirs("gtest")
