#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/mu/IVG/aubo_ws/devel_isolated/aubo_controller:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH='/home/mu/IVG/aubo_ws/devel_isolated/aubo_controller/lib:/home/mu/IVG/aubo_ws/devel_isolated/industrial_robot_client/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_planner/lib:/home/mu/IVG/aubo_ws/devel_isolated/simple_message/lib:/home/mu/IVG/aubo_ws/devel_isolated/industrial_utils/lib:/home/mu/IVG/aubo_ws/devel_isolated/industrial_trajectory_filters/lib:/home/mu/IVG/aubo_ws/devel_isolated/industrial_robot_simulator/lib:/home/mu/IVG/aubo_ws/devel_isolated/demo_driver/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_driver/lib:/home/mu/IVG/aubo_ws/devel_isolated/industrial_msgs/lib:/home/mu/IVG/aubo_ws/devel_isolated/industrial_deprecated/lib:/home/mu/IVG/aubo_ws/devel_isolated/demo_interface/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_urdf/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_msgs/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_kinematics/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_gazebo/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_e5_moveit_config/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_description/lib:/home/mu/IVG/aubo_ws/devel_isolated/aubo_demo/lib:/home/mu/IVG/ws_moveit/install_isolated/lib:/home/mu/IVG/ros_catkin_ws/install_isolated/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/ur5e_gripper_control/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/ur5e_octomap_moveit/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/robotiq_description/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/image_data_bridge/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/gazebo_grasp_plugin_ros/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/feedback_bridge/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/demo_driver/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/aubo_driver_ros2/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/aubo_demo/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/aubo_ros2_trajectory_action/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/visual_pose_estimation/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/realsense2_camera_msgs/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/percipio_camera_interface/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/percipio_camera/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/interface/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/gazebo_version_helpers/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/demo_interface/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/aubo_msgs/lib:/home/mu/IVG2.0/aubo_ros2_ws/install/aubo_dashboard_msgs/lib:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/humble/opt/rviz_ogre_vendor/lib:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/lib:/home/mu/.local/lib/python3.13/site-packages/nvidia/cudnn/lib:/home/mu/.local/lib/python3.13/site-packages/nvidia/cufft/lib:/home/mu/.local/lib/python3.13/site-packages/nvidia/cublas/lib:/home/mu/.local/lib/python3.13/site-packages/nvidia/cuda_runtime/lib:/usr/local/cuda-12.1/lib64:/usr/local/cuda-11.8/lib64'
export PKG_CONFIG_PATH="/home/mu/IVG/aubo_ws/devel_isolated/aubo_controller/lib/pkgconfig:$PKG_CONFIG_PATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/mu/IVG/aubo_ws/devel_isolated/aubo_controller/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/mu/IVG/aubo_ws/src/aubo_robot/aubo_robot/aubo_controller:$ROS_PACKAGE_PATH"