// Generated by gencpp from file demo_interface/ExecuteTrajectory.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_EXECUTETRAJECTORY_H
#define DEMO_INTERFACE_MESSAGE_EXECUTETRAJECTORY_H

#include <ros/service_traits.h>


#include <demo_interface/ExecuteTrajectoryRequest.h>
#include <demo_interface/ExecuteTrajectoryResponse.h>


namespace demo_interface
{

struct ExecuteTrajectory
{

typedef ExecuteTrajectoryRequest Request;
typedef ExecuteTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteTrajectory
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::ExecuteTrajectory > {
  static const char* value()
  {
    return "141b3c90cc65183a9295539645f2c064";
  }

  static const char* value(const ::demo_interface::ExecuteTrajectory&) { return value(); }
};

template<>
struct DataType< ::demo_interface::ExecuteTrajectory > {
  static const char* value()
  {
    return "demo_interface/ExecuteTrajectory";
  }

  static const char* value(const ::demo_interface::ExecuteTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::ExecuteTrajectoryRequest> should match
// service_traits::MD5Sum< ::demo_interface::ExecuteTrajectory >
template<>
struct MD5Sum< ::demo_interface::ExecuteTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::ExecuteTrajectory >::value();
  }
  static const char* value(const ::demo_interface::ExecuteTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::ExecuteTrajectoryRequest> should match
// service_traits::DataType< ::demo_interface::ExecuteTrajectory >
template<>
struct DataType< ::demo_interface::ExecuteTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::ExecuteTrajectory >::value();
  }
  static const char* value(const ::demo_interface::ExecuteTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::ExecuteTrajectoryResponse> should match
// service_traits::MD5Sum< ::demo_interface::ExecuteTrajectory >
template<>
struct MD5Sum< ::demo_interface::ExecuteTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::ExecuteTrajectory >::value();
  }
  static const char* value(const ::demo_interface::ExecuteTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::ExecuteTrajectoryResponse> should match
// service_traits::DataType< ::demo_interface::ExecuteTrajectory >
template<>
struct DataType< ::demo_interface::ExecuteTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::ExecuteTrajectory >::value();
  }
  static const char* value(const ::demo_interface::ExecuteTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_EXECUTETRAJECTORY_H
