// Generated by gencpp from file demo_interface/GetCurrentState.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_GETCURRENTSTATE_H
#define DEMO_INTERFACE_MESSAGE_GETCURRENTSTATE_H

#include <ros/service_traits.h>


#include <demo_interface/GetCurrentStateRequest.h>
#include <demo_interface/GetCurrentStateResponse.h>


namespace demo_interface
{

struct GetCurrentState
{

typedef GetCurrentStateRequest Request;
typedef GetCurrentStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentState
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::GetCurrentState > {
  static const char* value()
  {
    return "54871f675804e280e9a4e64601214b7d";
  }

  static const char* value(const ::demo_interface::GetCurrentState&) { return value(); }
};

template<>
struct DataType< ::demo_interface::GetCurrentState > {
  static const char* value()
  {
    return "demo_interface/GetCurrentState";
  }

  static const char* value(const ::demo_interface::GetCurrentState&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::GetCurrentStateRequest> should match
// service_traits::MD5Sum< ::demo_interface::GetCurrentState >
template<>
struct MD5Sum< ::demo_interface::GetCurrentStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::GetCurrentState >::value();
  }
  static const char* value(const ::demo_interface::GetCurrentStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::GetCurrentStateRequest> should match
// service_traits::DataType< ::demo_interface::GetCurrentState >
template<>
struct DataType< ::demo_interface::GetCurrentStateRequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::GetCurrentState >::value();
  }
  static const char* value(const ::demo_interface::GetCurrentStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::GetCurrentStateResponse> should match
// service_traits::MD5Sum< ::demo_interface::GetCurrentState >
template<>
struct MD5Sum< ::demo_interface::GetCurrentStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::GetCurrentState >::value();
  }
  static const char* value(const ::demo_interface::GetCurrentStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::GetCurrentStateResponse> should match
// service_traits::DataType< ::demo_interface::GetCurrentState >
template<>
struct DataType< ::demo_interface::GetCurrentStateResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::GetCurrentState >::value();
  }
  static const char* value(const ::demo_interface::GetCurrentStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_GETCURRENTSTATE_H
