// Generated by gencpp from file demo_interface/GetCurrentStateResponse.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_GETCURRENTSTATERESPONSE_H
#define DEMO_INTERFACE_MESSAGE_GETCURRENTSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace demo_interface
{
template <class ContainerAllocator>
struct GetCurrentStateResponse_
{
  typedef GetCurrentStateResponse_<ContainerAllocator> Type;

  GetCurrentStateResponse_()
    : success(false)
    , joint_position_rad()
    , cartesian_position()
    , velocity()
    , message()  {
    }
  GetCurrentStateResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , joint_position_rad(_alloc)
    , cartesian_position(_alloc)
    , velocity(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_position_rad_type;
  _joint_position_rad_type joint_position_rad;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _cartesian_position_type;
  _cartesian_position_type cartesian_position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_type;
  _velocity_type velocity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentStateResponse_

typedef ::demo_interface::GetCurrentStateResponse_<std::allocator<void> > GetCurrentStateResponse;

typedef boost::shared_ptr< ::demo_interface::GetCurrentStateResponse > GetCurrentStateResponsePtr;
typedef boost::shared_ptr< ::demo_interface::GetCurrentStateResponse const> GetCurrentStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator1> & lhs, const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.joint_position_rad == rhs.joint_position_rad &&
    lhs.cartesian_position == rhs.cartesian_position &&
    lhs.velocity == rhs.velocity &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator1> & lhs, const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54871f675804e280e9a4e64601214b7d";
  }

  static const char* value(const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54871f675804e280ULL;
  static const uint64_t static_value2 = 0xe9a4e64601214b7dULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/GetCurrentStateResponse";
  }

  static const char* value(const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float64[] joint_position_rad\n"
"geometry_msgs/Pose cartesian_position\n"
"float64[] velocity\n"
"string message\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.joint_position_rad);
      stream.next(m.cartesian_position);
      stream.next(m.velocity);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::GetCurrentStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::GetCurrentStateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_position_rad: ";
    if (v.joint_position_rad.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_position_rad.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_position_rad[i]);
    }
    if (v.joint_position_rad.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cartesian_position: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.cartesian_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    if (v.velocity.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.velocity[i]);
    }
    if (v.velocity.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_GETCURRENTSTATERESPONSE_H
