// Generated by gencpp from file demo_interface/PlanTrajectory.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_PLANTRAJECTORY_H
#define DEMO_INTERFACE_MESSAGE_PLANTRAJECTORY_H

#include <ros/service_traits.h>


#include <demo_interface/PlanTrajectoryRequest.h>
#include <demo_interface/PlanTrajectoryResponse.h>


namespace demo_interface
{

struct PlanTrajectory
{

typedef PlanTrajectoryRequest Request;
typedef PlanTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanTrajectory
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::PlanTrajectory > {
  static const char* value()
  {
    return "07df15be4b07a5a918366cc9c76a3ccd";
  }

  static const char* value(const ::demo_interface::PlanTrajectory&) { return value(); }
};

template<>
struct DataType< ::demo_interface::PlanTrajectory > {
  static const char* value()
  {
    return "demo_interface/PlanTrajectory";
  }

  static const char* value(const ::demo_interface::PlanTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::PlanTrajectoryRequest> should match
// service_traits::MD5Sum< ::demo_interface::PlanTrajectory >
template<>
struct MD5Sum< ::demo_interface::PlanTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::PlanTrajectory >::value();
  }
  static const char* value(const ::demo_interface::PlanTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::PlanTrajectoryRequest> should match
// service_traits::DataType< ::demo_interface::PlanTrajectory >
template<>
struct DataType< ::demo_interface::PlanTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::PlanTrajectory >::value();
  }
  static const char* value(const ::demo_interface::PlanTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::PlanTrajectoryResponse> should match
// service_traits::MD5Sum< ::demo_interface::PlanTrajectory >
template<>
struct MD5Sum< ::demo_interface::PlanTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::PlanTrajectory >::value();
  }
  static const char* value(const ::demo_interface::PlanTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::PlanTrajectoryResponse> should match
// service_traits::DataType< ::demo_interface::PlanTrajectory >
template<>
struct DataType< ::demo_interface::PlanTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::PlanTrajectory >::value();
  }
  static const char* value(const ::demo_interface::PlanTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_PLANTRAJECTORY_H
