// Generated by gencpp from file demo_interface/PlanTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_PLANTRAJECTORYRESPONSE_H
#define DEMO_INTERFACE_MESSAGE_PLANTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace demo_interface
{
template <class ContainerAllocator>
struct PlanTrajectoryResponse_
{
  typedef PlanTrajectoryResponse_<ContainerAllocator> Type;

  PlanTrajectoryResponse_()
    : success(false)
    , trajectory()
    , planning_time(0.0)
    , message()  {
    }
  PlanTrajectoryResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , trajectory(_alloc)
    , planning_time(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef float _planning_time_type;
  _planning_time_type planning_time;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanTrajectoryResponse_

typedef ::demo_interface::PlanTrajectoryResponse_<std::allocator<void> > PlanTrajectoryResponse;

typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryResponse > PlanTrajectoryResponsePtr;
typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryResponse const> PlanTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator1> & lhs, const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.trajectory == rhs.trajectory &&
    lhs.planning_time == rhs.planning_time &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator1> & lhs, const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b473b52d160d5a4af175e589436f196";
  }

  static const char* value(const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b473b52d160d5a4ULL;
  static const uint64_t static_value2 = 0xaf175e589436f196ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/PlanTrajectoryResponse";
  }

  static const char* value(const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"trajectory_msgs/JointTrajectory trajectory\n"
"float32 planning_time\n"
"string message\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.trajectory);
      stream.next(m.planning_time);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::PlanTrajectoryResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory: ";
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "planning_time: ";
    Printer<float>::stream(s, indent + "  ", v.planning_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_PLANTRAJECTORYRESPONSE_H
