// Generated by gencpp from file demo_interface/ReadRobotIOResponse.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_READROBOTIORESPONSE_H
#define DEMO_INTERFACE_MESSAGE_READROBOTIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct ReadRobotIOResponse_
{
  typedef ReadRobotIOResponse_<ContainerAllocator> Type;

  ReadRobotIOResponse_()
    : success(false)
    , value(0.0)
    , message()  {
    }
  ReadRobotIOResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , value(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef double _value_type;
  _value_type value;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadRobotIOResponse_

typedef ::demo_interface::ReadRobotIOResponse_<std::allocator<void> > ReadRobotIOResponse;

typedef boost::shared_ptr< ::demo_interface::ReadRobotIOResponse > ReadRobotIOResponsePtr;
typedef boost::shared_ptr< ::demo_interface::ReadRobotIOResponse const> ReadRobotIOResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator1> & lhs, const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.value == rhs.value &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator1> & lhs, const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4578b31c1e59f9e1beb8709ba78b7124";
  }

  static const char* value(const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4578b31c1e59f9e1ULL;
  static const uint64_t static_value2 = 0xbeb8709ba78b7124ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/ReadRobotIOResponse";
  }

  static const char* value(const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float64 value\n"
"string message\n"
"\n"
"\n"
;
  }

  static const char* value(const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.value);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadRobotIOResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::ReadRobotIOResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::ReadRobotIOResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_READROBOTIORESPONSE_H
