// Generated by gencpp from file demo_interface/RobotIOStatus.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_ROBOTIOSTATUS_H
#define DEMO_INTERFACE_MESSAGE_ROBOTIOSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <demo_interface/ToolIOStatus.h>

namespace demo_interface
{
template <class ContainerAllocator>
struct RobotIOStatus_
{
  typedef RobotIOStatus_<ContainerAllocator> Type;

  RobotIOStatus_()
    : header()
    , digital_inputs()
    , digital_outputs()
    , analog_inputs()
    , analog_outputs()
    , tool_io_status()
    , is_connected(false)  {
    }
  RobotIOStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , digital_inputs(_alloc)
    , digital_outputs(_alloc)
    , analog_inputs(_alloc)
    , analog_outputs(_alloc)
    , tool_io_status(_alloc)
    , is_connected(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _digital_inputs_type;
  _digital_inputs_type digital_inputs;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _digital_outputs_type;
  _digital_outputs_type digital_outputs;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _analog_inputs_type;
  _analog_inputs_type analog_inputs;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _analog_outputs_type;
  _analog_outputs_type analog_outputs;

   typedef  ::demo_interface::ToolIOStatus_<ContainerAllocator>  _tool_io_status_type;
  _tool_io_status_type tool_io_status;

   typedef uint8_t _is_connected_type;
  _is_connected_type is_connected;





  typedef boost::shared_ptr< ::demo_interface::RobotIOStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::RobotIOStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotIOStatus_

typedef ::demo_interface::RobotIOStatus_<std::allocator<void> > RobotIOStatus;

typedef boost::shared_ptr< ::demo_interface::RobotIOStatus > RobotIOStatusPtr;
typedef boost::shared_ptr< ::demo_interface::RobotIOStatus const> RobotIOStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::RobotIOStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::RobotIOStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::RobotIOStatus_<ContainerAllocator1> & lhs, const ::demo_interface::RobotIOStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.digital_inputs == rhs.digital_inputs &&
    lhs.digital_outputs == rhs.digital_outputs &&
    lhs.analog_inputs == rhs.analog_inputs &&
    lhs.analog_outputs == rhs.analog_outputs &&
    lhs.tool_io_status == rhs.tool_io_status &&
    lhs.is_connected == rhs.is_connected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::RobotIOStatus_<ContainerAllocator1> & lhs, const ::demo_interface::RobotIOStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::RobotIOStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::RobotIOStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::RobotIOStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "241d2a7d7ac2df6c1d3ad9602be6f25a";
  }

  static const char* value(const ::demo_interface::RobotIOStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x241d2a7d7ac2df6cULL;
  static const uint64_t static_value2 = 0x1d3ad9602be6f25aULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/RobotIOStatus";
  }

  static const char* value(const ::demo_interface::RobotIOStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool[] digital_inputs\n"
"bool[] digital_outputs\n"
"float32[] analog_inputs\n"
"float32[] analog_outputs\n"
"ToolIOStatus tool_io_status\n"
"bool is_connected\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: demo_interface/ToolIOStatus\n"
"bool[] digital_inputs\n"
"bool[] digital_outputs\n"
"float32[] analog_inputs\n"
"float32[] analog_outputs\n"
"\n"
;
  }

  static const char* value(const ::demo_interface::RobotIOStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.digital_inputs);
      stream.next(m.digital_outputs);
      stream.next(m.analog_inputs);
      stream.next(m.analog_outputs);
      stream.next(m.tool_io_status);
      stream.next(m.is_connected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotIOStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::RobotIOStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::RobotIOStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "digital_inputs: ";
    if (v.digital_inputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.digital_inputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.digital_inputs[i]);
    }
    if (v.digital_inputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "digital_outputs: ";
    if (v.digital_outputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.digital_outputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.digital_outputs[i]);
    }
    if (v.digital_outputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "analog_inputs: ";
    if (v.analog_inputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.analog_inputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.analog_inputs[i]);
    }
    if (v.analog_inputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "analog_outputs: ";
    if (v.analog_outputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.analog_outputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.analog_outputs[i]);
    }
    if (v.analog_outputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tool_io_status: ";
    Printer< ::demo_interface::ToolIOStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.tool_io_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_connected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_ROBOTIOSTATUS_H
