// Generated by gencpp from file demo_interface/RobotStatus.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_ROBOTSTATUS_H
#define DEMO_INTERFACE_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace demo_interface
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : header()
    , is_online(false)
    , enable(false)
    , in_motion(false)
    , planning_status()
    , joint_position_rad()
    , joint_position_deg()
    , cartesian_position()  {
      joint_position_rad.assign(0.0);

      joint_position_deg.assign(0.0);
  }
  RobotStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_online(false)
    , enable(false)
    , in_motion(false)
    , planning_status(_alloc)
    , joint_position_rad()
    , joint_position_deg()
    , cartesian_position(_alloc)  {
  (void)_alloc;
      joint_position_rad.assign(0.0);

      joint_position_deg.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_online_type;
  _is_online_type is_online;

   typedef uint8_t _enable_type;
  _enable_type enable;

   typedef uint8_t _in_motion_type;
  _in_motion_type in_motion;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _planning_status_type;
  _planning_status_type planning_status;

   typedef boost::array<double, 6>  _joint_position_rad_type;
  _joint_position_rad_type joint_position_rad;

   typedef boost::array<double, 6>  _joint_position_deg_type;
  _joint_position_deg_type joint_position_deg;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _cartesian_position_type;
  _cartesian_position_type cartesian_position;





  typedef boost::shared_ptr< ::demo_interface::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::demo_interface::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::demo_interface::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::demo_interface::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::RobotStatus_<ContainerAllocator1> & lhs, const ::demo_interface::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_online == rhs.is_online &&
    lhs.enable == rhs.enable &&
    lhs.in_motion == rhs.in_motion &&
    lhs.planning_status == rhs.planning_status &&
    lhs.joint_position_rad == rhs.joint_position_rad &&
    lhs.joint_position_deg == rhs.joint_position_deg &&
    lhs.cartesian_position == rhs.cartesian_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::RobotStatus_<ContainerAllocator1> & lhs, const ::demo_interface::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cf9bff7fe374641a90823ee8d3a68eb";
  }

  static const char* value(const ::demo_interface::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cf9bff7fe374641ULL;
  static const uint64_t static_value2 = 0xa90823ee8d3a68ebULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/RobotStatus";
  }

  static const char* value(const ::demo_interface::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool is_online\n"
"bool enable\n"
"bool in_motion\n"
"string planning_status\n"
"float64[6] joint_position_rad\n"
"float64[6] joint_position_deg\n"
"geometry_msgs/Pose cartesian_position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::demo_interface::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_online);
      stream.next(m.enable);
      stream.next(m.in_motion);
      stream.next(m.planning_status);
      stream.next(m.joint_position_rad);
      stream.next(m.joint_position_deg);
      stream.next(m.cartesian_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::RobotStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_online: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_online);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "in_motion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.in_motion);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "planning_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.planning_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_position_rad: ";
    if (v.joint_position_rad.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_position_rad.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_position_rad[i]);
    }
    if (v.joint_position_rad.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_position_deg: ";
    if (v.joint_position_deg.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_position_deg.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_position_deg[i]);
    }
    if (v.joint_position_deg.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cartesian_position: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.cartesian_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_ROBOTSTATUS_H
