// Generated by gencpp from file demo_interface/SetRobotIOResponse.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_SETROBOTIORESPONSE_H
#define DEMO_INTERFACE_MESSAGE_SETROBOTIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct SetRobotIOResponse_
{
  typedef SetRobotIOResponse_<ContainerAllocator> Type;

  SetRobotIOResponse_()
    : success(false)
    , error_code(0)
    , message()  {
    }
  SetRobotIOResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotIOResponse_

typedef ::demo_interface::SetRobotIOResponse_<std::allocator<void> > SetRobotIOResponse;

typedef boost::shared_ptr< ::demo_interface::SetRobotIOResponse > SetRobotIOResponsePtr;
typedef boost::shared_ptr< ::demo_interface::SetRobotIOResponse const> SetRobotIOResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::SetRobotIOResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::SetRobotIOResponse_<ContainerAllocator1> & lhs, const ::demo_interface::SetRobotIOResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::SetRobotIOResponse_<ContainerAllocator1> & lhs, const ::demo_interface::SetRobotIOResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9df8f352a4ad3d1b171a2f58ee3b8ad6";
  }

  static const char* value(const ::demo_interface::SetRobotIOResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9df8f352a4ad3d1bULL;
  static const uint64_t static_value2 = 0x171a2f58ee3b8ad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/SetRobotIOResponse";
  }

  static const char* value(const ::demo_interface::SetRobotIOResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"int32 error_code\n"
"string message\n"
"\n"
"\n"
;
  }

  static const char* value(const ::demo_interface::SetRobotIOResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotIOResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::SetRobotIOResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::SetRobotIOResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_SETROBOTIORESPONSE_H
