// Generated by gencpp from file demo_interface/SetRobotEnable.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_SETROBOTENABLE_H
#define DEMO_INTERFACE_MESSAGE_SETROBOTENABLE_H

#include <ros/service_traits.h>


#include <demo_interface/SetRobotEnableRequest.h>
#include <demo_interface/SetRobotEnableResponse.h>


namespace demo_interface
{

struct SetRobotEnable
{

typedef SetRobotEnableRequest Request;
typedef SetRobotEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobotEnable
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::SetRobotEnable > {
  static const char* value()
  {
    return "e0593992fefd6b0d91d0bf002fc60a2a";
  }

  static const char* value(const ::demo_interface::SetRobotEnable&) { return value(); }
};

template<>
struct DataType< ::demo_interface::SetRobotEnable > {
  static const char* value()
  {
    return "demo_interface/SetRobotEnable";
  }

  static const char* value(const ::demo_interface::SetRobotEnable&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::SetRobotEnableRequest> should match
// service_traits::MD5Sum< ::demo_interface::SetRobotEnable >
template<>
struct MD5Sum< ::demo_interface::SetRobotEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::SetRobotEnable >::value();
  }
  static const char* value(const ::demo_interface::SetRobotEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::SetRobotEnableRequest> should match
// service_traits::DataType< ::demo_interface::SetRobotEnable >
template<>
struct DataType< ::demo_interface::SetRobotEnableRequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::SetRobotEnable >::value();
  }
  static const char* value(const ::demo_interface::SetRobotEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::SetRobotEnableResponse> should match
// service_traits::MD5Sum< ::demo_interface::SetRobotEnable >
template<>
struct MD5Sum< ::demo_interface::SetRobotEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::SetRobotEnable >::value();
  }
  static const char* value(const ::demo_interface::SetRobotEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::SetRobotEnableResponse> should match
// service_traits::DataType< ::demo_interface::SetRobotEnable >
template<>
struct DataType< ::demo_interface::SetRobotEnableResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::SetRobotEnable >::value();
  }
  static const char* value(const ::demo_interface::SetRobotEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_SETROBOTENABLE_H
