// Generated by gencpp from file demo_interface/ToolIOStatus.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_TOOLIOSTATUS_H
#define DEMO_INTERFACE_MESSAGE_TOOLIOSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct ToolIOStatus_
{
  typedef ToolIOStatus_<ContainerAllocator> Type;

  ToolIOStatus_()
    : digital_inputs()
    , digital_outputs()
    , analog_inputs()
    , analog_outputs()  {
    }
  ToolIOStatus_(const ContainerAllocator& _alloc)
    : digital_inputs(_alloc)
    , digital_outputs(_alloc)
    , analog_inputs(_alloc)
    , analog_outputs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _digital_inputs_type;
  _digital_inputs_type digital_inputs;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _digital_outputs_type;
  _digital_outputs_type digital_outputs;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _analog_inputs_type;
  _analog_inputs_type analog_inputs;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _analog_outputs_type;
  _analog_outputs_type analog_outputs;





  typedef boost::shared_ptr< ::demo_interface::ToolIOStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::ToolIOStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ToolIOStatus_

typedef ::demo_interface::ToolIOStatus_<std::allocator<void> > ToolIOStatus;

typedef boost::shared_ptr< ::demo_interface::ToolIOStatus > ToolIOStatusPtr;
typedef boost::shared_ptr< ::demo_interface::ToolIOStatus const> ToolIOStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::ToolIOStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::ToolIOStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::ToolIOStatus_<ContainerAllocator1> & lhs, const ::demo_interface::ToolIOStatus_<ContainerAllocator2> & rhs)
{
  return lhs.digital_inputs == rhs.digital_inputs &&
    lhs.digital_outputs == rhs.digital_outputs &&
    lhs.analog_inputs == rhs.analog_inputs &&
    lhs.analog_outputs == rhs.analog_outputs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::ToolIOStatus_<ContainerAllocator1> & lhs, const ::demo_interface::ToolIOStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::ToolIOStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::ToolIOStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::ToolIOStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "219be75bd56b8ebdca0dfa526c3803be";
  }

  static const char* value(const ::demo_interface::ToolIOStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x219be75bd56b8ebdULL;
  static const uint64_t static_value2 = 0xca0dfa526c3803beULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/ToolIOStatus";
  }

  static const char* value(const ::demo_interface::ToolIOStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] digital_inputs\n"
"bool[] digital_outputs\n"
"float32[] analog_inputs\n"
"float32[] analog_outputs\n"
"\n"
;
  }

  static const char* value(const ::demo_interface::ToolIOStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digital_inputs);
      stream.next(m.digital_outputs);
      stream.next(m.analog_inputs);
      stream.next(m.analog_outputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToolIOStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::ToolIOStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::ToolIOStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "digital_inputs: ";
    if (v.digital_inputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.digital_inputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.digital_inputs[i]);
    }
    if (v.digital_inputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "digital_outputs: ";
    if (v.digital_outputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.digital_outputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.digital_outputs[i]);
    }
    if (v.digital_outputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "analog_inputs: ";
    if (v.analog_inputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.analog_inputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.analog_inputs[i]);
    }
    if (v.analog_inputs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "analog_outputs: ";
    if (v.analog_outputs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.analog_outputs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.analog_outputs[i]);
    }
    if (v.analog_outputs.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_TOOLIOSTATUS_H
