set(_CATKIN_CURRENT_PACKAGE "pybind11_catkin")
set(pybind11_catkin_VERSION "2.10.3")
set(pybind11_catkin_MAINTAINER "Wolfgang Merkt <wolfgang@robots.ox.ac.uk>")
set(pybind11_catkin_PACKAGE_FORMAT "3")
set(pybind11_catkin_BUILD_DEPENDS "pybind11-dev")
set(pybind11_catkin_BUILD_EXPORT_DEPENDS "eigen" "python" "python-numpy" "python3" "python3-numpy" "pybind11-dev")
set(pybind11_catkin_BUILDTOOL_DEPENDS "catkin")
set(pybind11_catkin_BUILDTOOL_EXPORT_DEPENDS )
set(pybind11_catkin_EXEC_DEPENDS "pybind11-dev")
set(pybind11_catkin_RUN_DEPENDS "pybind11-dev" "eigen" "python" "python-numpy" "python3" "python3-numpy")
set(pybind11_catkin_TEST_DEPENDS )
set(pybind11_catkin_DOC_DEPENDS )
set(pybind11_catkin_URL_WEBSITE "")
set(pybind11_catkin_URL_BUGTRACKER "")
set(pybind11_catkin_URL_REPOSITORY "")
set(pybind11_catkin_DEPRECATED "")