# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ws_moveit/src/realtime_tools
# Build directory: /home/mu/IVG/ws_moveit/build_isolated/realtime_tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_realtime_tools_gtest_realtime_box_tests "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/gtest-realtime_box_tests.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/realtime_tools/lib/realtime_tools/realtime_box_tests --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/gtest-realtime_box_tests.xml")
set_tests_properties(_ctest_realtime_tools_gtest_realtime_box_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;63;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;23;catkin_add_gmock;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;0;")
add_test(_ctest_realtime_tools_gtest_realtime_buffer_tests "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/gtest-realtime_buffer_tests.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/realtime_tools/lib/realtime_tools/realtime_buffer_tests --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/gtest-realtime_buffer_tests.xml")
set_tests_properties(_ctest_realtime_tools_gtest_realtime_buffer_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;63;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;26;catkin_add_gmock;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;0;")
add_test(_ctest_realtime_tools_gtest_realtime_clock_tests "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/gtest-realtime_clock_tests.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/realtime_tools/lib/realtime_tools/realtime_clock_tests --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/gtest-realtime_clock_tests.xml")
set_tests_properties(_ctest_realtime_tools_gtest_realtime_clock_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;63;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;29;catkin_add_gmock;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;0;")
add_test(_ctest_realtime_tools_rostest_test_realtime_publisher.test "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/rostest-test_realtime_publisher.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/realtime_tools --package=realtime_tools --results-filename test_realtime_publisher.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results\" /home/mu/IVG/ws_moveit/src/realtime_tools/test/realtime_publisher.test ")
set_tests_properties(_ctest_realtime_tools_rostest_test_realtime_publisher.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;119;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;33;add_rostest_gmock;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;0;")
add_test(_ctest_realtime_tools_rostest_test_realtime_server_goal_handle.test "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results/realtime_tools/rostest-test_realtime_server_goal_handle.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/realtime_tools --package=realtime_tools --results-filename test_realtime_server_goal_handle.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/realtime_tools/test_results\" /home/mu/IVG/ws_moveit/src/realtime_tools/test/realtime_server_goal_handle.test ")
set_tests_properties(_ctest_realtime_tools_rostest_test_realtime_server_goal_handle.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;119;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;38;add_rostest_gmock;/home/mu/IVG/ws_moveit/src/realtime_tools/CMakeLists.txt;0;")
subdirs("gtest")
