# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from demo_interface/RobotIOStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import demo_interface.msg
import std_msgs.msg

class RobotIOStatus(genpy.Message):
  _md5sum = "241d2a7d7ac2df6c1d3ad9602be6f25a"
  _type = "demo_interface/RobotIOStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool[] digital_inputs
bool[] digital_outputs
float32[] analog_inputs
float32[] analog_outputs
ToolIOStatus tool_io_status
bool is_connected


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: demo_interface/ToolIOStatus
bool[] digital_inputs
bool[] digital_outputs
float32[] analog_inputs
float32[] analog_outputs

"""
  __slots__ = ['header','digital_inputs','digital_outputs','analog_inputs','analog_outputs','tool_io_status','is_connected']
  _slot_types = ['std_msgs/Header','bool[]','bool[]','float32[]','float32[]','demo_interface/ToolIOStatus','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,digital_inputs,digital_outputs,analog_inputs,analog_outputs,tool_io_status,is_connected

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotIOStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.digital_inputs is None:
        self.digital_inputs = []
      if self.digital_outputs is None:
        self.digital_outputs = []
      if self.analog_inputs is None:
        self.analog_inputs = []
      if self.analog_outputs is None:
        self.analog_outputs = []
      if self.tool_io_status is None:
        self.tool_io_status = demo_interface.msg.ToolIOStatus()
      if self.is_connected is None:
        self.is_connected = False
    else:
      self.header = std_msgs.msg.Header()
      self.digital_inputs = []
      self.digital_outputs = []
      self.analog_inputs = []
      self.analog_outputs = []
      self.tool_io_status = demo_interface.msg.ToolIOStatus()
      self.is_connected = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.digital_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.digital_inputs))
      length = len(self.digital_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.digital_outputs))
      length = len(self.analog_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.analog_inputs))
      length = len(self.analog_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.analog_outputs))
      length = len(self.tool_io_status.digital_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.tool_io_status.digital_inputs))
      length = len(self.tool_io_status.digital_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.tool_io_status.digital_outputs))
      length = len(self.tool_io_status.analog_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.tool_io_status.analog_inputs))
      length = len(self.tool_io_status.analog_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.tool_io_status.analog_outputs))
      _x = self.is_connected
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.tool_io_status is None:
        self.tool_io_status = demo_interface.msg.ToolIOStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.digital_inputs = s.unpack(str[start:end])
      self.digital_inputs = list(map(bool, self.digital_inputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.digital_outputs = s.unpack(str[start:end])
      self.digital_outputs = list(map(bool, self.digital_outputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.analog_inputs = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.analog_outputs = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.digital_inputs = s.unpack(str[start:end])
      self.tool_io_status.digital_inputs = list(map(bool, self.tool_io_status.digital_inputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.digital_outputs = s.unpack(str[start:end])
      self.tool_io_status.digital_outputs = list(map(bool, self.tool_io_status.digital_outputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.analog_inputs = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.analog_outputs = s.unpack(str[start:end])
      start = end
      end += 1
      (self.is_connected,) = _get_struct_B().unpack(str[start:end])
      self.is_connected = bool(self.is_connected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.digital_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.digital_inputs.tostring())
      length = len(self.digital_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.digital_outputs.tostring())
      length = len(self.analog_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.analog_inputs.tostring())
      length = len(self.analog_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.analog_outputs.tostring())
      length = len(self.tool_io_status.digital_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.tool_io_status.digital_inputs.tostring())
      length = len(self.tool_io_status.digital_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.tool_io_status.digital_outputs.tostring())
      length = len(self.tool_io_status.analog_inputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.tool_io_status.analog_inputs.tostring())
      length = len(self.tool_io_status.analog_outputs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.tool_io_status.analog_outputs.tostring())
      _x = self.is_connected
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.tool_io_status is None:
        self.tool_io_status = demo_interface.msg.ToolIOStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.digital_inputs = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.digital_inputs = list(map(bool, self.digital_inputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.digital_outputs = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.digital_outputs = list(map(bool, self.digital_outputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.analog_inputs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.analog_outputs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.digital_inputs = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.tool_io_status.digital_inputs = list(map(bool, self.tool_io_status.digital_inputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.digital_outputs = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.tool_io_status.digital_outputs = list(map(bool, self.tool_io_status.digital_outputs))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.analog_inputs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tool_io_status.analog_outputs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 1
      (self.is_connected,) = _get_struct_B().unpack(str[start:end])
      self.is_connected = bool(self.is_connected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
