# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from demo_interface/RobotStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class RobotStatus(genpy.Message):
  _md5sum = "5cf9bff7fe374641a90823ee8d3a68eb"
  _type = "demo_interface/RobotStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool is_online
bool enable
bool in_motion
string planning_status
float64[6] joint_position_rad
float64[6] joint_position_deg
geometry_msgs/Pose cartesian_position


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','is_online','enable','in_motion','planning_status','joint_position_rad','joint_position_deg','cartesian_position']
  _slot_types = ['std_msgs/Header','bool','bool','bool','string','float64[6]','float64[6]','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,is_online,enable,in_motion,planning_status,joint_position_rad,joint_position_deg,cartesian_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.is_online is None:
        self.is_online = False
      if self.enable is None:
        self.enable = False
      if self.in_motion is None:
        self.in_motion = False
      if self.planning_status is None:
        self.planning_status = ''
      if self.joint_position_rad is None:
        self.joint_position_rad = [0.] * 6
      if self.joint_position_deg is None:
        self.joint_position_deg = [0.] * 6
      if self.cartesian_position is None:
        self.cartesian_position = geometry_msgs.msg.Pose()
    else:
      self.header = std_msgs.msg.Header()
      self.is_online = False
      self.enable = False
      self.in_motion = False
      self.planning_status = ''
      self.joint_position_rad = [0.] * 6
      self.joint_position_deg = [0.] * 6
      self.cartesian_position = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.is_online, _x.enable, _x.in_motion))
      _x = self.planning_status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_6d().pack(*self.joint_position_rad))
      buff.write(_get_struct_6d().pack(*self.joint_position_deg))
      _x = self
      buff.write(_get_struct_7d().pack(_x.cartesian_position.position.x, _x.cartesian_position.position.y, _x.cartesian_position.position.z, _x.cartesian_position.orientation.x, _x.cartesian_position.orientation.y, _x.cartesian_position.orientation.z, _x.cartesian_position.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cartesian_position is None:
        self.cartesian_position = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.is_online, _x.enable, _x.in_motion,) = _get_struct_3B().unpack(str[start:end])
      self.is_online = bool(self.is_online)
      self.enable = bool(self.enable)
      self.in_motion = bool(self.in_motion)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.planning_status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.planning_status = str[start:end]
      start = end
      end += 48
      self.joint_position_rad = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.joint_position_deg = _get_struct_6d().unpack(str[start:end])
      _x = self
      start = end
      end += 56
      (_x.cartesian_position.position.x, _x.cartesian_position.position.y, _x.cartesian_position.position.z, _x.cartesian_position.orientation.x, _x.cartesian_position.orientation.y, _x.cartesian_position.orientation.z, _x.cartesian_position.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.is_online, _x.enable, _x.in_motion))
      _x = self.planning_status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.joint_position_rad.tostring())
      buff.write(self.joint_position_deg.tostring())
      _x = self
      buff.write(_get_struct_7d().pack(_x.cartesian_position.position.x, _x.cartesian_position.position.y, _x.cartesian_position.position.z, _x.cartesian_position.orientation.x, _x.cartesian_position.orientation.y, _x.cartesian_position.orientation.z, _x.cartesian_position.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cartesian_position is None:
        self.cartesian_position = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.is_online, _x.enable, _x.in_motion,) = _get_struct_3B().unpack(str[start:end])
      self.is_online = bool(self.is_online)
      self.enable = bool(self.enable)
      self.in_motion = bool(self.in_motion)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.planning_status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.planning_status = str[start:end]
      start = end
      end += 48
      self.joint_position_rad = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.joint_position_deg = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      _x = self
      start = end
      end += 56
      (_x.cartesian_position.position.x, _x.cartesian_position.position.y, _x.cartesian_position.position.z, _x.cartesian_position.orientation.x, _x.cartesian_position.orientation.y, _x.cartesian_position.orientation.z, _x.cartesian_position.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
