# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test
# Build directory: /home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_commander_rostest_test_python_moveit_commander.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test_results/moveit_commander/rostest-test_python_moveit_commander.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_commander --package=moveit_commander --results-filename test_python_moveit_commander.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/python_moveit_commander.test ")
set_tests_properties(_ctest_moveit_commander_rostest_test_python_moveit_commander.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/CMakeLists.txt;4;add_rostest;/home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/CMakeLists.txt;0;")
add_test(_ctest_moveit_commander_rostest_test_python_moveit_commander_ns.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test_results/moveit_commander/rostest-test_python_moveit_commander_ns.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_commander --package=moveit_commander --results-filename test_python_moveit_commander_ns.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/python_moveit_commander_ns.test ")
set_tests_properties(_ctest_moveit_commander_rostest_test_python_moveit_commander_ns.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/CMakeLists.txt;5;add_rostest;/home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/CMakeLists.txt;0;")
add_test(_ctest_moveit_commander_rostest_test_python_time_parameterization.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test_results/moveit_commander/rostest-test_python_time_parameterization.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_commander --package=moveit_commander --results-filename test_python_time_parameterization.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_commander/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/python_time_parameterization.test ")
set_tests_properties(_ctest_moveit_commander_rostest_test_python_time_parameterization.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/CMakeLists.txt;6;add_rostest;/home/mu/IVG/ws_moveit/src/moveit/moveit_commander/test/CMakeLists.txt;0;")
