string request_id
uint64 expected_revision
bool auto_start_enabled
bool execution_enabled
bool grasp_enabled
bool tool_enabled
---
bool accepted
string message
uint64 revision
peach_harvest_msgs/HarvestState state
