/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    GraspControls: typeof import('./../components/grasp/GraspControls.vue')['default']
    PoseCard: typeof import('./../components/grasp/PoseCard.vue')['default']
    RobotStatusBar: typeof import('./../components/ivg/RobotStatusBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteNav: typeof import('./../components/ivg/SiteNav.vue')['default']
    ToolSwapBar: typeof import('./../components/grasp/ToolSwapBar.vue')['default']
  }
}
