/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    LatteControls: typeof import('./../components/latte/LatteControls.vue')['default']
    LatteCupConfigPanel: typeof import('./../components/latte/LatteCupConfigPanel.vue')['default']
    LattePatternSelector: typeof import('./../components/latte/LattePatternSelector.vue')['default']
    LattePourConfigPanel: typeof import('./../components/latte/LattePourConfigPanel.vue')['default']
    LatteTransformControls: typeof import('./../components/latte/LatteTransformControls.vue')['default']
    Robot3dViewer: typeof import('./../components/ivg/Robot3dViewer.vue')['default']
    RobotStatusBar: typeof import('./../components/ivg/RobotStatusBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteNav: typeof import('./../components/ivg/SiteNav.vue')['default']
    ToolSwapBar: typeof import('./../components/grasp/ToolSwapBar.vue')['default']
  }
}
