# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ws_moveit/src/geometry2/tf2
# Build directory: /home/mu/IVG/ws_moveit/build_isolated/tf2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf2_gtest_test_cache_unittest "/home/mu/IVG/ws_moveit/build_isolated/tf2/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_cache_unittest.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/tf2/lib/tf2/test_cache_unittest --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_cache_unittest.xml")
set_tests_properties(_ctest_tf2_gtest_test_cache_unittest PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;39;catkin_add_gtest;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;0;")
add_test(_ctest_tf2_gtest_test_static_cache_unittest "/home/mu/IVG/ws_moveit/build_isolated/tf2/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_static_cache_unittest.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/tf2/lib/tf2/test_static_cache_unittest --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_static_cache_unittest.xml")
set_tests_properties(_ctest_tf2_gtest_test_static_cache_unittest PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;43;catkin_add_gtest;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;0;")
add_test(_ctest_tf2_gtest_test_simple "/home/mu/IVG/ws_moveit/build_isolated/tf2/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_simple.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/tf2/lib/tf2/test_simple --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_simple.xml")
set_tests_properties(_ctest_tf2_gtest_test_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;47;catkin_add_gtest;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;0;")
add_test(_ctest_tf2_gtest_test_transform_datatypes "/home/mu/IVG/ws_moveit/build_isolated/tf2/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_transform_datatypes.xml" "--return-code" "/home/mu/IVG/ws_moveit/devel_isolated/tf2/lib/tf2/test_transform_datatypes --gtest_output=xml:/home/mu/IVG/ws_moveit/build_isolated/tf2/test_results/tf2/gtest-test_transform_datatypes.xml")
set_tests_properties(_ctest_tf2_gtest_test_transform_datatypes PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;56;catkin_add_gtest;/home/mu/IVG/ws_moveit/src/geometry2/tf2/CMakeLists.txt;0;")
subdirs("gtest")
