set(_CATKIN_CURRENT_PACKAGE "demo_interface")
set(demo_interface_VERSION "1.0.0")
set(demo_interface_MAINTAINER "User <user@example.com>")
set(demo_interface_PACKAGE_FORMAT "1")
set(demo_interface_BUILD_DEPENDS "message_generation" "std_msgs" "geometry_msgs" "trajectory_msgs" "roscpp")
set(demo_interface_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "trajectory_msgs")
set(demo_interface_BUILDTOOL_DEPENDS "catkin")
set(demo_interface_BUILDTOOL_EXPORT_DEPENDS )
set(demo_interface_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "trajectory_msgs")
set(demo_interface_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "trajectory_msgs")
set(demo_interface_TEST_DEPENDS )
set(demo_interface_DOC_DEPENDS )
set(demo_interface_URL_WEBSITE "")
set(demo_interface_URL_BUGTRACKER "")
set(demo_interface_URL_REPOSITORY "")
set(demo_interface_DEPRECATED "")