// Generated by gencpp from file demo_interface/GetCurrentStateRequest.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_GETCURRENTSTATEREQUEST_H
#define DEMO_INTERFACE_MESSAGE_GETCURRENTSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct GetCurrentStateRequest_
{
  typedef GetCurrentStateRequest_<ContainerAllocator> Type;

  GetCurrentStateRequest_()
    {
    }
  GetCurrentStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentStateRequest_

typedef ::demo_interface::GetCurrentStateRequest_<std::allocator<void> > GetCurrentStateRequest;

typedef boost::shared_ptr< ::demo_interface::GetCurrentStateRequest > GetCurrentStateRequestPtr;
typedef boost::shared_ptr< ::demo_interface::GetCurrentStateRequest const> GetCurrentStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::demo_interface::GetCurrentStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/GetCurrentStateRequest";
  }

  static const char* value(const ::demo_interface::GetCurrentStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::demo_interface::GetCurrentStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::GetCurrentStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::demo_interface::GetCurrentStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_GETCURRENTSTATEREQUEST_H
