// Generated by gencpp from file demo_interface/MoveToPose.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_MOVETOPOSE_H
#define DEMO_INTERFACE_MESSAGE_MOVETOPOSE_H

#include <ros/service_traits.h>


#include <demo_interface/MoveToPoseRequest.h>
#include <demo_interface/MoveToPoseResponse.h>


namespace demo_interface
{

struct MoveToPose
{

typedef MoveToPoseRequest Request;
typedef MoveToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPose
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::MoveToPose > {
  static const char* value()
  {
    return "13d651572c46e71643945d975979b6fc";
  }

  static const char* value(const ::demo_interface::MoveToPose&) { return value(); }
};

template<>
struct DataType< ::demo_interface::MoveToPose > {
  static const char* value()
  {
    return "demo_interface/MoveToPose";
  }

  static const char* value(const ::demo_interface::MoveToPose&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::MoveToPoseRequest> should match
// service_traits::MD5Sum< ::demo_interface::MoveToPose >
template<>
struct MD5Sum< ::demo_interface::MoveToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::MoveToPose >::value();
  }
  static const char* value(const ::demo_interface::MoveToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::MoveToPoseRequest> should match
// service_traits::DataType< ::demo_interface::MoveToPose >
template<>
struct DataType< ::demo_interface::MoveToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::MoveToPose >::value();
  }
  static const char* value(const ::demo_interface::MoveToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::MoveToPoseResponse> should match
// service_traits::MD5Sum< ::demo_interface::MoveToPose >
template<>
struct MD5Sum< ::demo_interface::MoveToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::MoveToPose >::value();
  }
  static const char* value(const ::demo_interface::MoveToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::MoveToPoseResponse> should match
// service_traits::DataType< ::demo_interface::MoveToPose >
template<>
struct DataType< ::demo_interface::MoveToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::MoveToPose >::value();
  }
  static const char* value(const ::demo_interface::MoveToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_MOVETOPOSE_H
