// Generated by gencpp from file demo_interface/MoveToPoseRequest.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_MOVETOPOSEREQUEST_H
#define DEMO_INTERFACE_MESSAGE_MOVETOPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace demo_interface
{
template <class ContainerAllocator>
struct MoveToPoseRequest_
{
  typedef MoveToPoseRequest_<ContainerAllocator> Type;

  MoveToPoseRequest_()
    : target_pose()
    , use_joints(false)
    , velocity_factor(0.0)
    , acceleration_factor(0.0)  {
    }
  MoveToPoseRequest_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)
    , use_joints(false)
    , velocity_factor(0.0)
    , acceleration_factor(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef uint8_t _use_joints_type;
  _use_joints_type use_joints;

   typedef float _velocity_factor_type;
  _velocity_factor_type velocity_factor;

   typedef float _acceleration_factor_type;
  _acceleration_factor_type acceleration_factor;





  typedef boost::shared_ptr< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPoseRequest_

typedef ::demo_interface::MoveToPoseRequest_<std::allocator<void> > MoveToPoseRequest;

typedef boost::shared_ptr< ::demo_interface::MoveToPoseRequest > MoveToPoseRequestPtr;
typedef boost::shared_ptr< ::demo_interface::MoveToPoseRequest const> MoveToPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::MoveToPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::MoveToPoseRequest_<ContainerAllocator1> & lhs, const ::demo_interface::MoveToPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_pose == rhs.target_pose &&
    lhs.use_joints == rhs.use_joints &&
    lhs.velocity_factor == rhs.velocity_factor &&
    lhs.acceleration_factor == rhs.acceleration_factor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::MoveToPoseRequest_<ContainerAllocator1> & lhs, const ::demo_interface::MoveToPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00a28e9e2a6c5b4a00ef87a9fb467542";
  }

  static const char* value(const ::demo_interface::MoveToPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00a28e9e2a6c5b4aULL;
  static const uint64_t static_value2 = 0x00ef87a9fb467542ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/MoveToPoseRequest";
  }

  static const char* value(const ::demo_interface::MoveToPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose target_pose\n"
"bool use_joints\n"
"float32 velocity_factor\n"
"float32 acceleration_factor\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::demo_interface::MoveToPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
      stream.next(m.use_joints);
      stream.next(m.velocity_factor);
      stream.next(m.acceleration_factor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::MoveToPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::MoveToPoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_joints: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_joints);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity_factor: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_factor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration_factor: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration_factor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_MOVETOPOSEREQUEST_H
