// Generated by gencpp from file demo_interface/PlanTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_PLANTRAJECTORYREQUEST_H
#define DEMO_INTERFACE_MESSAGE_PLANTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace demo_interface
{
template <class ContainerAllocator>
struct PlanTrajectoryRequest_
{
  typedef PlanTrajectoryRequest_<ContainerAllocator> Type;

  PlanTrajectoryRequest_()
    : target_pose()
    , use_joints(false)  {
    }
  PlanTrajectoryRequest_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)
    , use_joints(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef uint8_t _use_joints_type;
  _use_joints_type use_joints;





  typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanTrajectoryRequest_

typedef ::demo_interface::PlanTrajectoryRequest_<std::allocator<void> > PlanTrajectoryRequest;

typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryRequest > PlanTrajectoryRequestPtr;
typedef boost::shared_ptr< ::demo_interface::PlanTrajectoryRequest const> PlanTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator1> & lhs, const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_pose == rhs.target_pose &&
    lhs.use_joints == rhs.use_joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator1> & lhs, const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37144d5bbdb0e17dcf68bcb5b6275b64";
  }

  static const char* value(const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37144d5bbdb0e17dULL;
  static const uint64_t static_value2 = 0xcf68bcb5b6275b64ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/PlanTrajectoryRequest";
  }

  static const char* value(const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose target_pose\n"
"bool use_joints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
      stream.next(m.use_joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::PlanTrajectoryRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_joints: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_PLANTRAJECTORYREQUEST_H
