// Generated by gencpp from file demo_interface/ReadRobotIORequest.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_READROBOTIOREQUEST_H
#define DEMO_INTERFACE_MESSAGE_READROBOTIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct ReadRobotIORequest_
{
  typedef ReadRobotIORequest_<ContainerAllocator> Type;

  ReadRobotIORequest_()
    : io_type()
    , io_index(0)  {
    }
  ReadRobotIORequest_(const ContainerAllocator& _alloc)
    : io_type(_alloc)
    , io_index(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _io_type_type;
  _io_type_type io_type;

   typedef int32_t _io_index_type;
  _io_index_type io_index;





  typedef boost::shared_ptr< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReadRobotIORequest_

typedef ::demo_interface::ReadRobotIORequest_<std::allocator<void> > ReadRobotIORequest;

typedef boost::shared_ptr< ::demo_interface::ReadRobotIORequest > ReadRobotIORequestPtr;
typedef boost::shared_ptr< ::demo_interface::ReadRobotIORequest const> ReadRobotIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::ReadRobotIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::ReadRobotIORequest_<ContainerAllocator1> & lhs, const ::demo_interface::ReadRobotIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.io_type == rhs.io_type &&
    lhs.io_index == rhs.io_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::ReadRobotIORequest_<ContainerAllocator1> & lhs, const ::demo_interface::ReadRobotIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a92292e8000354f152bf5ec9d99d343c";
  }

  static const char* value(const ::demo_interface::ReadRobotIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa92292e8000354f1ULL;
  static const uint64_t static_value2 = 0x52bf5ec9d99d343cULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/ReadRobotIORequest";
  }

  static const char* value(const ::demo_interface::ReadRobotIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string io_type\n"
"int32 io_index\n"
;
  }

  static const char* value(const ::demo_interface::ReadRobotIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.io_type);
      stream.next(m.io_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadRobotIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::ReadRobotIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::ReadRobotIORequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "io_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.io_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.io_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_READROBOTIOREQUEST_H
