// Generated by gencpp from file demo_interface/ReadRobotIO.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_READROBOTIO_H
#define DEMO_INTERFACE_MESSAGE_READROBOTIO_H

#include <ros/service_traits.h>


#include <demo_interface/ReadRobotIORequest.h>
#include <demo_interface/ReadRobotIOResponse.h>


namespace demo_interface
{

struct ReadRobotIO
{

typedef ReadRobotIORequest Request;
typedef ReadRobotIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadRobotIO
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::ReadRobotIO > {
  static const char* value()
  {
    return "5d10bf6c42285a91d7053eb3125941e8";
  }

  static const char* value(const ::demo_interface::ReadRobotIO&) { return value(); }
};

template<>
struct DataType< ::demo_interface::ReadRobotIO > {
  static const char* value()
  {
    return "demo_interface/ReadRobotIO";
  }

  static const char* value(const ::demo_interface::ReadRobotIO&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::ReadRobotIORequest> should match
// service_traits::MD5Sum< ::demo_interface::ReadRobotIO >
template<>
struct MD5Sum< ::demo_interface::ReadRobotIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::ReadRobotIO >::value();
  }
  static const char* value(const ::demo_interface::ReadRobotIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::ReadRobotIORequest> should match
// service_traits::DataType< ::demo_interface::ReadRobotIO >
template<>
struct DataType< ::demo_interface::ReadRobotIORequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::ReadRobotIO >::value();
  }
  static const char* value(const ::demo_interface::ReadRobotIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::ReadRobotIOResponse> should match
// service_traits::MD5Sum< ::demo_interface::ReadRobotIO >
template<>
struct MD5Sum< ::demo_interface::ReadRobotIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::ReadRobotIO >::value();
  }
  static const char* value(const ::demo_interface::ReadRobotIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::ReadRobotIOResponse> should match
// service_traits::DataType< ::demo_interface::ReadRobotIO >
template<>
struct DataType< ::demo_interface::ReadRobotIOResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::ReadRobotIO >::value();
  }
  static const char* value(const ::demo_interface::ReadRobotIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_READROBOTIO_H
