// Generated by gencpp from file demo_interface/SetRobotIORequest.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_SETROBOTIOREQUEST_H
#define DEMO_INTERFACE_MESSAGE_SETROBOTIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct SetRobotIORequest_
{
  typedef SetRobotIORequest_<ContainerAllocator> Type;

  SetRobotIORequest_()
    : io_type()
    , io_index(0)
    , value(0.0)  {
    }
  SetRobotIORequest_(const ContainerAllocator& _alloc)
    : io_type(_alloc)
    , io_index(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _io_type_type;
  _io_type_type io_type;

   typedef int32_t _io_index_type;
  _io_index_type io_index;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::demo_interface::SetRobotIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::SetRobotIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotIORequest_

typedef ::demo_interface::SetRobotIORequest_<std::allocator<void> > SetRobotIORequest;

typedef boost::shared_ptr< ::demo_interface::SetRobotIORequest > SetRobotIORequestPtr;
typedef boost::shared_ptr< ::demo_interface::SetRobotIORequest const> SetRobotIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::SetRobotIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::SetRobotIORequest_<ContainerAllocator1> & lhs, const ::demo_interface::SetRobotIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.io_type == rhs.io_type &&
    lhs.io_index == rhs.io_index &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::SetRobotIORequest_<ContainerAllocator1> & lhs, const ::demo_interface::SetRobotIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::SetRobotIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::SetRobotIORequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::SetRobotIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d14c5359d5a6bcfa1747111fae77ea69";
  }

  static const char* value(const ::demo_interface::SetRobotIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd14c5359d5a6bcfaULL;
  static const uint64_t static_value2 = 0x1747111fae77ea69ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/SetRobotIORequest";
  }

  static const char* value(const ::demo_interface::SetRobotIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string io_type\n"
"int32 io_index\n"
"float64 value\n"
;
  }

  static const char* value(const ::demo_interface::SetRobotIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.io_type);
      stream.next(m.io_index);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::SetRobotIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::SetRobotIORequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "io_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.io_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.io_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_SETROBOTIOREQUEST_H
