// Generated by gencpp from file demo_interface/SetRobotIO.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_SETROBOTIO_H
#define DEMO_INTERFACE_MESSAGE_SETROBOTIO_H

#include <ros/service_traits.h>


#include <demo_interface/SetRobotIORequest.h>
#include <demo_interface/SetRobotIOResponse.h>


namespace demo_interface
{

struct SetRobotIO
{

typedef SetRobotIORequest Request;
typedef SetRobotIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobotIO
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::SetRobotIO > {
  static const char* value()
  {
    return "2e3250f0a25c75ced7db303a09e99be6";
  }

  static const char* value(const ::demo_interface::SetRobotIO&) { return value(); }
};

template<>
struct DataType< ::demo_interface::SetRobotIO > {
  static const char* value()
  {
    return "demo_interface/SetRobotIO";
  }

  static const char* value(const ::demo_interface::SetRobotIO&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::SetRobotIORequest> should match
// service_traits::MD5Sum< ::demo_interface::SetRobotIO >
template<>
struct MD5Sum< ::demo_interface::SetRobotIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::SetRobotIO >::value();
  }
  static const char* value(const ::demo_interface::SetRobotIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::SetRobotIORequest> should match
// service_traits::DataType< ::demo_interface::SetRobotIO >
template<>
struct DataType< ::demo_interface::SetRobotIORequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::SetRobotIO >::value();
  }
  static const char* value(const ::demo_interface::SetRobotIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::SetRobotIOResponse> should match
// service_traits::MD5Sum< ::demo_interface::SetRobotIO >
template<>
struct MD5Sum< ::demo_interface::SetRobotIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::SetRobotIO >::value();
  }
  static const char* value(const ::demo_interface::SetRobotIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::SetRobotIOResponse> should match
// service_traits::DataType< ::demo_interface::SetRobotIO >
template<>
struct DataType< ::demo_interface::SetRobotIOResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::SetRobotIO >::value();
  }
  static const char* value(const ::demo_interface::SetRobotIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_SETROBOTIO_H
