// Generated by gencpp from file demo_interface/SetSpeedFactorRequest.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_SETSPEEDFACTORREQUEST_H
#define DEMO_INTERFACE_MESSAGE_SETSPEEDFACTORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_interface
{
template <class ContainerAllocator>
struct SetSpeedFactorRequest_
{
  typedef SetSpeedFactorRequest_<ContainerAllocator> Type;

  SetSpeedFactorRequest_()
    : velocity_factor(0.0)  {
    }
  SetSpeedFactorRequest_(const ContainerAllocator& _alloc)
    : velocity_factor(0.0)  {
  (void)_alloc;
    }



   typedef float _velocity_factor_type;
  _velocity_factor_type velocity_factor;





  typedef boost::shared_ptr< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpeedFactorRequest_

typedef ::demo_interface::SetSpeedFactorRequest_<std::allocator<void> > SetSpeedFactorRequest;

typedef boost::shared_ptr< ::demo_interface::SetSpeedFactorRequest > SetSpeedFactorRequestPtr;
typedef boost::shared_ptr< ::demo_interface::SetSpeedFactorRequest const> SetSpeedFactorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator1> & lhs, const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.velocity_factor == rhs.velocity_factor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator1> & lhs, const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc69473a6482657d072116f1f5f7992b";
  }

  static const char* value(const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc69473a6482657dULL;
  static const uint64_t static_value2 = 0x072116f1f5f7992bULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_interface/SetSpeedFactorRequest";
  }

  static const char* value(const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocity_factor\n"
;
  }

  static const char* value(const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity_factor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpeedFactorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_interface::SetSpeedFactorRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "velocity_factor: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_factor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_SETSPEEDFACTORREQUEST_H
