// Generated by gencpp from file demo_interface/SetSpeedFactor.msg
// DO NOT EDIT!


#ifndef DEMO_INTERFACE_MESSAGE_SETSPEEDFACTOR_H
#define DEMO_INTERFACE_MESSAGE_SETSPEEDFACTOR_H

#include <ros/service_traits.h>


#include <demo_interface/SetSpeedFactorRequest.h>
#include <demo_interface/SetSpeedFactorResponse.h>


namespace demo_interface
{

struct SetSpeedFactor
{

typedef SetSpeedFactorRequest Request;
typedef SetSpeedFactorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeedFactor
} // namespace demo_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_interface::SetSpeedFactor > {
  static const char* value()
  {
    return "743f72e0c72310f8ab529ef4bb485765";
  }

  static const char* value(const ::demo_interface::SetSpeedFactor&) { return value(); }
};

template<>
struct DataType< ::demo_interface::SetSpeedFactor > {
  static const char* value()
  {
    return "demo_interface/SetSpeedFactor";
  }

  static const char* value(const ::demo_interface::SetSpeedFactor&) { return value(); }
};


// service_traits::MD5Sum< ::demo_interface::SetSpeedFactorRequest> should match
// service_traits::MD5Sum< ::demo_interface::SetSpeedFactor >
template<>
struct MD5Sum< ::demo_interface::SetSpeedFactorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::SetSpeedFactor >::value();
  }
  static const char* value(const ::demo_interface::SetSpeedFactorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::SetSpeedFactorRequest> should match
// service_traits::DataType< ::demo_interface::SetSpeedFactor >
template<>
struct DataType< ::demo_interface::SetSpeedFactorRequest>
{
  static const char* value()
  {
    return DataType< ::demo_interface::SetSpeedFactor >::value();
  }
  static const char* value(const ::demo_interface::SetSpeedFactorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_interface::SetSpeedFactorResponse> should match
// service_traits::MD5Sum< ::demo_interface::SetSpeedFactor >
template<>
struct MD5Sum< ::demo_interface::SetSpeedFactorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_interface::SetSpeedFactor >::value();
  }
  static const char* value(const ::demo_interface::SetSpeedFactorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_interface::SetSpeedFactorResponse> should match
// service_traits::DataType< ::demo_interface::SetSpeedFactor >
template<>
struct DataType< ::demo_interface::SetSpeedFactorResponse>
{
  static const char* value()
  {
    return DataType< ::demo_interface::SetSpeedFactor >::value();
  }
  static const char* value(const ::demo_interface::SetSpeedFactorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_INTERFACE_MESSAGE_SETSPEEDFACTOR_H
