[develop]
script_dir=$base/lib/peach_perception
[install]
install_scripts=$base/lib/peach_perception

[flake8]
exclude =
    peach_perception/scene_perception_parameters.py,
    peach_perception/target_reconstruction_parameters.py

[tool:pytest]
testpaths = test
[options.extras_require]
test =
    pytest
