set(_CATKIN_CURRENT_PACKAGE "aubo_urdf")
set(aubo_urdf_VERSION "1.0.0")
set(aubo_urdf_MAINTAINER " <TODO@email.com>")
set(aubo_urdf_PACKAGE_FORMAT "2")
set(aubo_urdf_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(aubo_urdf_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(aubo_urdf_BUILDTOOL_DEPENDS "catkin")
set(aubo_urdf_BUILDTOOL_EXPORT_DEPENDS )
set(aubo_urdf_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(aubo_urdf_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(aubo_urdf_TEST_DEPENDS )
set(aubo_urdf_DOC_DEPENDS )
set(aubo_urdf_URL_WEBSITE "")
set(aubo_urdf_URL_BUGTRACKER "")
set(aubo_urdf_URL_REPOSITORY "")
set(aubo_urdf_DEPRECATED "")