# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ros_catkin_ws/src/laser_geometry
# Build directory: /home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_laser_geometry_gtest_projection_test "/home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/test_results/laser_geometry/gtest-projection_test.xml" "--return-code" "/home/mu/IVG/ros_catkin_ws/devel_isolated/laser_geometry/lib/laser_geometry/projection_test --gtest_output=xml:/home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/test_results/laser_geometry/gtest-projection_test.xml")
set_tests_properties(_ctest_laser_geometry_gtest_projection_test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/mu/IVG/ros_catkin_ws/src/laser_geometry/CMakeLists.txt;42;catkin_add_gtest;/home/mu/IVG/ros_catkin_ws/src/laser_geometry/CMakeLists.txt;0;")
add_test(_ctest_laser_geometry_nosetests_test.projection_test.py "/home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/test_results/laser_geometry/nosetests-test.projection_test.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/test_results/laser_geometry" "/usr/bin/nosetests3 -P --process-timeout=60 /home/mu/IVG/ros_catkin_ws/src/laser_geometry/test/projection_test.py --with-xunit --xunit-file=/home/mu/IVG/ros_catkin_ws/build_isolated/laser_geometry/test_results/laser_geometry/nosetests-test.projection_test.py.xml")
set_tests_properties(_ctest_laser_geometry_nosetests_test.projection_test.py PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/src/laser_geometry/CMakeLists.txt;46;catkin_add_nosetests;/home/mu/IVG/ros_catkin_ws/src/laser_geometry/CMakeLists.txt;0;")
subdirs("gtest")
