# CMake generated Testfile for 
# Source directory: /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor
# Build directory: /home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/planning_scene_monitor
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_ros_planning_rostest_planning_scene_monitor_test_current_state_monitor.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/test_results/moveit_ros_planning/rostest-planning_scene_monitor_test_current_state_monitor.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning --package=moveit_ros_planning --results-filename planning_scene_monitor_test_current_state_monitor.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor/test/current_state_monitor.test ")
set_tests_properties(_ctest_moveit_ros_planning_rostest_planning_scene_monitor_test_current_state_monitor.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor/CMakeLists.txt;21;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor/CMakeLists.txt;0;")
add_test(_ctest_moveit_ros_planning_rostest_planning_scene_monitor_test_planning_scene_monitor.test "/home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/test_results/moveit_ros_planning/rostest-planning_scene_monitor_test_planning_scene_monitor.xml" "--return-code" "/usr/bin/python3 /home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning --package=moveit_ros_planning --results-filename planning_scene_monitor_test_planning_scene_monitor.xml --results-base-dir \"/home/mu/IVG/ws_moveit/build_isolated/moveit_ros_planning/test_results\" /home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor/test/planning_scene_monitor.test ")
set_tests_properties(_ctest_moveit_ros_planning_rostest_planning_scene_monitor_test_planning_scene_monitor.test PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/mu/IVG/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor/CMakeLists.txt;24;add_rostest_gtest;/home/mu/IVG/ws_moveit/src/moveit/moveit_ros/planning/planning_scene_monitor/CMakeLists.txt;0;")
