<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tool_changer</name>
  <version>1.0.0</version>
  <description>快换与手爪管理：gripper0 ↔ gripper2 双向自动快换，工具状态管理</description>

  <maintainer email="user@example.com">User</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>tool_changer_interface</depend>
  <depend>demo_interface</depend>
  <depend>aubo_msgs</depend>
  <depend>moveit_core</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_msgs</depend>
  <depend>geometric_shapes</depend>
  <depend>yaml_cpp_vendor</depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
