# CMake generated Testfile for 
# Source directory: /home/mu/IVG/aubo_ws/src/aubo_robot/industrial_core/industrial_robot_client
# Build directory: /home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_industrial_robot_client_gtest_utest_robot_client "/home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/test_results/industrial_robot_client/gtest-utest_robot_client.xml" "--return-code" "/home/mu/IVG/aubo_ws/devel_isolated/industrial_robot_client/lib/industrial_robot_client/utest_robot_client --gtest_output=xml:/home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/test_results/industrial_robot_client/gtest-utest_robot_client.xml")
set_tests_properties(_ctest_industrial_robot_client_gtest_utest_robot_client PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/mu/IVG/aubo_ws/src/aubo_robot/industrial_core/industrial_robot_client/CMakeLists.txt;162;catkin_add_gtest;/home/mu/IVG/aubo_ws/src/aubo_robot/industrial_core/industrial_robot_client/CMakeLists.txt;0;")
add_test(_ctest_industrial_robot_client_roslaunch-check_test_roslaunch_test.xml "/home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/test_results/industrial_robot_client/roslaunch-check_test_roslaunch_test.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/test_results/industrial_robot_client" "/home/mu/IVG/ros_catkin_ws/install_isolated/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/mu/IVG/aubo_ws/build_isolated/industrial_robot_client/test_results/industrial_robot_client/roslaunch-check_test_roslaunch_test.xml.xml\" \"/home/mu/IVG/aubo_ws/src/aubo_robot/industrial_core/industrial_robot_client/test/roslaunch_test.xml\" ")
set_tests_properties(_ctest_industrial_robot_client_roslaunch-check_test_roslaunch_test.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/mu/IVG/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/mu/IVG/ros_catkin_ws/install_isolated/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/mu/IVG/aubo_ws/src/aubo_robot/industrial_core/industrial_robot_client/CMakeLists.txt;170;roslaunch_add_file_check;/home/mu/IVG/aubo_ws/src/aubo_robot/industrial_core/industrial_robot_client/CMakeLists.txt;0;")
subdirs("gtest")
