set(_CATKIN_CURRENT_PACKAGE "demo_driver")
set(demo_driver_VERSION "1.0.0")
set(demo_driver_MAINTAINER "User <user@example.com>")
set(demo_driver_PACKAGE_FORMAT "1")
set(demo_driver_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "industrial_msgs" "demo_interface" "aubo_msgs" "message_runtime" "moveit_core" "moveit_ros_planning_interface" "tf2_ros" "tf2_geometry_msgs")
set(demo_driver_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "industrial_msgs" "demo_interface" "aubo_msgs" "message_runtime" "moveit_core" "moveit_ros_planning_interface" "tf2_ros" "tf2_geometry_msgs")
set(demo_driver_BUILDTOOL_DEPENDS "catkin")
set(demo_driver_BUILDTOOL_EXPORT_DEPENDS )
set(demo_driver_EXEC_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "industrial_msgs" "demo_interface" "aubo_msgs" "message_runtime" "moveit_core" "moveit_ros_planning_interface" "tf2_ros" "tf2_geometry_msgs")
set(demo_driver_RUN_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "industrial_msgs" "demo_interface" "aubo_msgs" "message_runtime" "moveit_core" "moveit_ros_planning_interface" "tf2_ros" "tf2_geometry_msgs")
set(demo_driver_TEST_DEPENDS )
set(demo_driver_DOC_DEPENDS )
set(demo_driver_URL_WEBSITE "")
set(demo_driver_URL_BUGTRACKER "")
set(demo_driver_URL_REPOSITORY "")
set(demo_driver_DEPRECATED "")